---
title: "DIY Hydrometric"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Arduino Data Loggers

### Data logger

### Sensors

1.  **Hydrometric** (In-stream)

    [OTT-PLS 500](https://www.ott.com/products/water-level-1/ott-pls-500-pressure-level-sensor-2494/) (\~2500$CAD) Water level, Water temperature   
    [Hydros-21](https://www.metergroup.com/en/meter-environment/products/hydros-21-water-level-sensor-conductivity-temperature-depth) (\~900$CAD) Water level, Water temperature, Electrical conductivity   
    [DFRobot](https://www.dfrobot.com/product-1863.html) (\~50$CAD) Water level   
    [Analite 195](https://www.esonetyellowpages.com/manuals/manual-nep180_series_1254507878.pdf) (\~2500$CAD) Turbidity   
    [DS18B20](https://www.adafruit.com/product/381) (\~10$CAD) Water temperature

2.  **Hydrometric** (Non-contact)

    [MaxBotix 7052](https://www.digikey.ca/en/products/detail/maxbotix-inc/MB7052-100/7896790) (\~170$CAD) Water level

3.  **Climate** (Temp/RH/Snow)

    [SHT-30](https://www.digikey.ca/en/products/detail/adafruit-industries-llc/4099/10230011) (\~40$CAD) [MaxBotix 7052](https://www.digikey.ca/en/products/detail/maxbotix-inc/MB7052-100/7896790) (\~170$CAD) Water level

### Modems

1.  [RockBlock Iridium](https://www.groundcontrol.com/en/product/rockblock-9603-compact-plug-and-play-satellite-transmitter/) (\~500)
2.  [SWARM](https://www.sparkfun.com/products/21287) (\~400)
3.  [Particle Boron LTE](https://docs.particle.io/boron/) (\~100)

### How-to build

1.  Order equipment

    |                                                      | **Cost** | **Hydros-21 or OTT PLS** | **Hydros-21 or OTT PLS + Analite** | Source                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
    |------------------------------------------------------|----------|--------------------------|------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    | **Data logger**                                      |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | Adafruit Feather M0 Adalogger                        | 27.96    | 1                        | 1                                  | [Digikey](https://www.digikey.ca/en/products/detail/adafruit-industries-llc/2796/5804105)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
    | Adafruit Featherwing Terminal Block                  | 20.95    | 1                        | 1                                  | [Digikey](https://www.digikey.ca/en/products/detail/adafruit-industries-llc/2926/5959339)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
    | Adafruit Latching Relay                              | 11.14    | 1                        | 2                                  | [Digikey](https://www.digikey.ca/en/products/detail/adafruit-industries-llc/2923/5979892)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
    | Adafruit RTC PCF8523                                 | 9.74     | 1                        | 1                                  | [Digikey](https://www.digikey.ca/en/products/detail/adafruit-industries-llc/3295/6238007)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
    | Terminal Block 2P Side Ent 2.54MM PCB                | 0.95     | 2                        | 4                                  | [Digikey](https://www.digikey.ca/en/products/detail/adafruit-industries-llc/2138/6827101)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
    | 32 GB Micro SD                                       | 11.29    | 1                        | 1                                  | [Amazon](https://www.amazon.ca/Sandisk-SDSQUAR-032G-GN6MA-Ultra-Micro-Adapter/dp/B073JWXGNT/ref=asc_df_B073JWXGNT/?tag=googleshopc0c-20&linkCode=df0&hvadid=292991886665&hvpos=&hvnetw=g&hvrand=15742836061598794976&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9001480&hvtargid=pla-348080513499&psc=1)                                                                                                                                                                                                                                                                                                                                                          |
    | CR1220 12MM DIAMETER 3V LITHIUM (PACK OF 8)          | 8.89     | 0.125                    | 0.125                              | [Amazon](https://www.amazon.ca/CR1220-ECR1220-Lithium-Cell-Batteries/dp/B07542B14R/ref=sr_1_1_sspa?crid=2LFB4XHHCVEET&keywords=cr1220&qid=1690869545&s=electronics&sprefix=cr1220%2Celectronics%2C139&sr=1-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1)                                                                                                                                                                                                                                                                                                                                                                                                                           |
    |                                                      |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | **Power (3.7V LiPo)**                                |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | LITHIUM ION BATTERY PACK - 3.7V 6600MAH              | 24.50    | 1                        | 1                                  | [Adafruit](https://www.adafruit.com/product/353)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
    | FIRE RETARDANT LIPO BAGS                             | 10.99    | 1                        | 1                                  | [Amazon](https://www.amazon.ca/gp/product/B08KW2TL5G/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
    | BATT CHG SOLAR 3.7V/4.2V 1.5A                        | 22.33    | 1                        | 1                                  | [Digikey](https://www.digikey.ca/en/products/detail/adafruit-industries-llc/4755/13231325)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
    | 5V 10W Solar Panel                                   | 121.08   | 1                        | 1                                  | [Mouser](https://www.mouser.ca/c/power/solar-panels-solar-cells/?m=Adafruit)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
    | THERMISTOR NTC 10KOHM 3950K                          | 5.61     | 1                        | 1                                  | [Digikey](https://www.digikey.ca/en/products/detail/adafruit-industries-llc/372/6051772)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
    | JST-PH 2-PIN JUMPER CABLE - 100M                     | 1.33     | 1                        | 1                                  | [Digikey](https://www.digikey.ca/en/products/detail/adafruit-industries-llc/4714/13175532)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
    | CABLE ASSY 5.5X2.1MM M/F 3'                          | 6.12     | 1                        | 1                                  | [Digikey](https://www.digikey.ca/en/products/detail/tensility-international-corp/CA-2216/1129479)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
    | 3.5 / 1.3MM OR 3.8 / 1.1MM TO 5.                     | 2.10     | 1                        | 1                                  | [Digikey](https://www.digikey.ca/en/products/detail/adafruit-industries-llc/2788/7244959)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
    |                                                      |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | **Power (12V)**                                      |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | 12V SEALED LEAD ACID BATTERY                         | 33.72    |                          | 1                                  | [Digikey](https://www.digikey.ca/en/products/detail/power-sonic-corporation/PS-1270%2520F1/13577496)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
    | CRIMP CONNECTORS                                     | 0.09     |                          | 2                                  | [Amazon](https://www.amazon.ca/dp/B0B4H54KPS/ref=sspa_dk_detail_1?psc=1&pd_rd_i=B0B4H54KPS&pd_rd_w=H6tjt&content-id=amzn1.sym.d8c43617-c625-45bd-a63f-ad8715c2c055&pf_rd_p=d8c43617-c625-45bd-a63f-ad8715c2c055&pf_rd_r=P07VXJ55N2Q3YRMZF5ZC&pd_rd_wg=MMRHw&pd_rd_r=9a85380a-cfb0-4c70-923b-382be7c91366&s=hi&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWw)                                                                                                                                                                                                                                                                                                                                  |
    |                                                      |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | **Telemetry**                                        |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | RockBLOCK 9603N - Iridium SatComm Module             | 499.99   | 1                        | 1                                  | [Digikey](https://www.digikey.ca/en/products/detail/sparkfun-electronics/WRL-14498/7902308)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
    | RockBLOCK 9603 Accessory Cable                       | 6.94     | 1                        | 1                                  | [Digikey](https://www.digikey.ca/en/products/detail/sparkfun-electronics/CAB-14720/9373056)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
    | RF ANT 1.6GHZ MODULE SMA ML MAG                      | 118.23   | 1                        | 1                                  | [Digikey](https://www.digikey.ca/en/products/detail/taoglas-limited/IAA-01-121111/2332661)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
    | PN22222                                              | 0.60     | 1                        | 1                                  | [Adafruit](https://www.adafruit.com/product/756)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
    | Metal plate                                          | 11.96    | 0.5                      | 0.5                                | [Home Depot](https://www.homedepot.ca/product/paulin-6-x-18-inch-16-gauge-steel-sheet/1000861865?eid=PS_GOOGLE_D25H%20-%20E-Comm_GGL_Shopping_PLA_EN_Hardware_Hardware__PRODUCT_GROUP_pla-1640865175826&gclid=CjwKCAjwt52mBhB5EiwA05YKo3DtEeMO5ZfuEN30yGz32r5iy7peNJhYW1x35Y_PcesGT0Z2AFNZ9xoCLDgQAvD_BwE&gclsrc=aw.ds)                                                                                                                                                                                                                                                                                                                                                            |
    |                                                      |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | **Bulk units**                                       |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | 24 AWG HOOKUP WIRE (25 FT)                           | 41.97    | 0.05                     | 0.05                               | [Digikey](https://www.digikey.ca/en/products/detail/adafruit-industries-llc/3174/6198257)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
    | DESICANTS                                            | 16.99    | 0.1                      | 0.1                                | [Amazon](https://www.amazon.ca/Dry-Premium-Packets-Desiccants-Dehumidifier/dp/B00VJ02VMK/ref=sxts_rp_s_1_0?content-id=amzn1.sym.852cfc8b-1c03-4e66-a255-23c00e9b0072%3Aamzn1.sym.852cfc8b-1c03-4e66-a255-23c00e9b0072&cv_ct_cx=desiccants&hvadid=249751390777&hvdev=c&hvlocphy=9001480&hvnetw=g&hvqmt=e&hvrand=17567589881241820109&hvtargid=kwd-324000731735&hydadcr=20848_10090735&keywords=desiccants&pd_rd_i=B00VJ02VMK&pd_rd_r=39c2c56a-01bd-4f72-bb7d-82119c257a2a&pd_rd_w=Yz2w3&pd_rd_wg=4lUgM&pf_rd_p=852cfc8b-1c03-4e66-a255-23c00e9b0072&pf_rd_r=Z9N6WBCQEEKBS6K19JR7&qid=1690871226&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&sr=1-1-f0029781-b79b-4b60-9cb0-eeda4dea34d6) |
    | SHRINK WRAP                                          | 13.99    | 0.05                     | 0.05                               | [Amazon](https://www.amazon.ca/xrime-850pcs-Shrink-Tubing-Assortment/dp/B07MJLJKVC/ref=asc_df_B07MJLJKVC/?tag=googleshopc0c-20&linkCode=df0&hvadid=292944236606&hvpos=&hvnetw=g&hvrand=3385782868889843414&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9001480&hvtargid=pla-646785267770&psc=1)                                                                                                                                                                                                                                                                                                                                                                    |
    |                                                      |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | **Sensors**                                          |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | WATER LEVEL (DFROBOT GRAVITY THROW IN)               | 43.90    |                          |                                    | [DFRobot](https://www.dfrobot.com/product-1863.html)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
    | WATERPROOF DS18B20 DIGITAL TEMPE                     | 14.87    |                          |                                    | [Digikey](https://www.digikey.ca/en/products/detail/adafruit-industries-llc/381/5875807?utm_adgroup=&utm_source=google&utm_medium=cpc&utm_campaign=PMax%20Product_High%20ROAS%20Categories&utm_term=&productid=5875807&gclid=CjwKCAjwt52mBhB5EiwA05YKozeIlabzOJ1IZA8qk2wajMdVl04w2rwf7ikKKQpnhPEU0MIYt67w_RoCKBsQAvD_BwE)                                                                                                                                                                                                                                                                                                                                                          |
    | TURBIDITY SENSOR                                     | 13.87    |                          |                                    | [Digikey](https://www.digikey.ca/en/products/detail/dfrobot/SEN0189/6588606)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
    | MB7554 (SELF-CLEANING, SERIAL) SCXL-MAXSONAR-WRS     |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | MB7354 (NOT SELF-CLEANING, SERIAL) HRXL-MAXSONAR-WRS |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | MB7369 (SERIAL) FOR WATER                            |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | SHT-30 MESH-PROTECTED WEATHER-PR (TEMP/RH)           | 36.18    |                          |                                    | [Mouser](https://www.mouser.ca/ProductDetail/Adafruit/4099?qs=PzGy0jfpSMvuluNPiarQpg%3D%3D)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
    | Analite 195                                          |          |                          | 1                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | Analite spare wiper                                  |          |                          | 1                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | OTT-PLS 500 (LEVEL, TEMP)                            |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | HYDROS-21 (LEVEL, TEMP, EC)                          |          | 1                        | 1                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    |                                                      |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | **Mounting Hardware**                                |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | BLACK NYLON SCREW AND STAND-OFF                      | 25.32    | 1.27                     | 0.05                               | [Digikey](https://www.digikey.ca/en/products/detail/adafruit-industries-llc/3299/6596885)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
    | 1/8-inch x 48-inch x 48-inch Hardboard Panel         | 14.86    | 0.125                    | 0.125                              | [Home Depot](https://www.homedepot.ca/product/alexandria-moulding-1-8-inch-x-48-inch-x-48-inch-hardboard-panel/1000132235?rrec=true)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
    |                                                      |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | **Enclosure**                                        |          |                          |                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | CABLE GLAND 3-6.5MM M12 NYLON                        | 2.75     | 1                        | 1                                  | [Digikey](https://www.digikey.ca/en/products/detail/amphenol-industrial-operations/AIO-CSM12/3904956)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
    | CABLE GLAND 5-10MM M18 NYLON                         | 3.24     | 1                        | 1                                  | [Digikey](https://www.digikey.ca/en/products/detail/amphenol-industrial-operations/AIO-CSM18/3904948)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |

2.  Set-up work station

3.  Solder components

4.  Assemble

5.  Register modem

6.  Bench test

## Code

1.  

## How-To

### Reset

### Download data

### Upload New Code

### Measure Battery Voltage

## Backend

### Database

### Shiny App
